<!-- <form action="/student/" method="post">
<label for="">Product Name</label>
<input type="text" name="pname">
<label for="">Quantity</label>
<input type="number" name="qty">
<button type="submit" value="submit" class="btn btn-primary">Add</button>

</form> -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=h1, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Refresh and Insert Data in Db </h1>
</body>
</html>