<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Phalcon Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <?php
    echo $this->tag->stylesheetLink('https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css', true);
    echo $this->tag->stylesheetLink("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css", true);
    ?>
</head>

<body>
    <div class="container-fluid">
        <?php echo $this->getContent(); ?>
    </div>
</body>

</html>